numpy example

In [ ]:
import numpy as np

In [ ]:
ZeroD=np.array(46)
print (type(ZeroD))

<class 'numpy.ndarray'>


In [ ]:
OneD=np.array([12,45,89,47,45,78,89])
OneD

array([12, 45, 89, 47, 45, 78, 89])

In [ ]:
np.ndim(OneD)

1

In [ ]:
TwoD=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
TwoD

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.ndim(TwoD)

2

In [ ]:
ThreeD=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]]])
ThreeD

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4]]])

In [ ]:
np.ndim(ThreeD)

3

In [ ]:
np.size(TwoD)

16

In [ ]:
np.shape(TwoD)

(4, 4)

In [ ]:
print(type(ThreeD))

<class 'numpy.ndarray'>


In [ ]:
print(len(OneD))

7


In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(1,25,15)
np.linspace(4,50,7)

array([ 4.        , 11.66666667, 19.33333333, 27.        , 34.66666667,
       42.33333333, 50.        ])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(4)

array([0.85043347, 0.4211465 , 0.7163964 , 0.93070654])

In [ ]:
np.random.rand(4,2,5)

array([[[0.88194196, 0.03413824, 0.18253095, 0.16693398, 0.2364822 ],
        [0.05394914, 0.09495416, 0.15367617, 0.13109243, 0.02399574]],

       [[0.05891913, 0.41504209, 0.40115828, 0.68954442, 0.75967036],
        [0.79792162, 0.87187365, 0.45698015, 0.16267862, 0.32158483]],

       [[0.0071519 , 0.97433156, 0.78506746, 0.16415126, 0.80623798],
        [0.64778646, 0.81237998, 0.19509763, 0.98767114, 0.76296312]],

       [[0.6895359 , 0.48613737, 0.43010827, 0.13474642, 0.33816639],
        [0.60578109, 0.24233494, 0.01688502, 0.29599578, 0.6547131 ]]])

In [ ]:
np.random.randint(1,6)

1

In [ ]:
np.random.randint(1,6,20)


array([4, 2, 1, 2, 4, 3, 1, 2, 1, 1, 4, 4, 3, 5, 2, 3, 4, 4, 5, 2])

In [ ]:
b=np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
b.shape

(15,)

In [ ]:
b.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [ ]:
np.min(b)

np.int64(1)

In [ ]:
np.max(b)

np.int64(29)

In [ ]:
b.min()

np.int64(1)

In [ ]:
b.max()

np.int64(29)

In [ ]:
b.argmax()

np.int64(14)